blueprints/auth.py
from flask import Blueprint, render_template, request, jsonify, redirect, url_for, session
from models import UserModel, EmailCaptchaModel, TreeholeModel
from exts import db, mail
from werkzeug.security import generate_password_hash, check_password_hash
from flask_mail import Message
import string
import random
from .forms import RegisterForm, LoginForm, UpdatePasswordForm, UpdateUsernameForm
from decorators import login_required

auth_bp = Blueprint('auth', __name__, url_prefix='/auth')

@auth_bp.route('/login', methods = ['GET', 'POST'])
def login():
    if request.method == 'GET':
        return render_template('login.html')
    else:
        form = LoginForm(request.form)
        if form.validate():
            email = form.email.data
            password = form.password.data
            user = UserModel.query.filter_by(email = email).first()
            if not user:
                print('用户不存在')
                return redirect(url_for('auth.login'))
            if check_password_hash(user.pswd, password):
                #cookie只能存放少量数据
                #cookie一般用来保存登录授权的东西
                session['user_id'] = user.id
                return redirect('/')
            else:
                print('密码错误')
                return redirect(url_for('auth.login'))
        else:
            print(form.errors)
            return redirect(url_for('auth.login'))
        
@auth_bp.route('/logout')
def logout():
    session.clear()
    return redirect(url_for('auth.login'))

@auth_bp.route('/manage')
def manage():
    return render_template('manage.html')
    

#GET：从服务器获取数据，POST：向服务器提交数据
@auth_bp.route('/register', methods=['GET', 'POST'])
def register():
    if request.method == 'GET':
        return render_template('register.html')
    else:
        #验证
        form = RegisterForm(request.form)
        if form.validate():
            email = form.email.data
            password = form.password.data
            table = (string.ascii_lowercase + string.digits) * 8
            username = ''.join(random.sample(table, 8))
            user = UserModel(username = username, pswd = generate_password_hash(password), email = email)
            db.session.add(user)
            db.session.commit()
            return redirect(url_for('auth.login'))
        else:
            print(form.errors)
            return redirect(url_for('auth.register'))
        
    

@auth_bp.route('/captcha')
def send_captcha():
    email = request.args.get('email')
    src = string.digits * 6
    captcha = "".join(random.sample(src, 6))
    message = Message(subject='TreeholeBUAA验证码', recipients = [email], body=f'[TreeholeBUAA]\n{captcha}是您的验证码，请妥善保管。')
    mail.send(message)
    email_captcha = EmailCaptchaModel(email = email, captcha = captcha)
    db.session.add(email_captcha)
    db.session.commit()
    return jsonify({'code':200,'msg':'', 'data': None})

@auth_bp.route('/update/pswd' , methods=['GET', 'POST'])
@login_required
def update_pswd():
    if request.method == 'GET':
        return render_template('update_pswd.html')
    else:
        form = UpdatePasswordForm(request.form)
        if form.validate():
           key = session.get('user_id')
           user = UserModel.query.get(key)
           new_password = form.new_password.data
           user.pswd = generate_password_hash(new_password)
           db.session.commit()
           session.clear()
           return redirect(url_for('auth.login'))
        else:
            print(form.errors)
            return redirect(url_for('auth.update_pswd'))
        
@auth_bp.route('/update/username', methods=['GET', 'POST'])
@login_required
def update_username():
    if request.method == 'GET':
        return render_template('update_username.html')
    else:
        form = UpdateUsernameForm(request.form)
        if form.validate():
            key = session.get('user_id')
            user = UserModel.query.get(key)
            table = (string.ascii_lowercase + string.digits) * 8
            new_username = ''.join(random.sample(table, 8))
            user.username = new_username
            db.session.commit()
            session.clear()
            return redirect(url_for('auth.login'))
        else:
            print(form.errors)
            return redirect(url_for('auth.manage'))

@auth_bp.route('/manage/treeholes', methods=['GET'])
@login_required
def manage_treeholes():
    user = UserModel.query.get(session.get('user_id'))
    return render_template('my_treeholes.html', treeholes = user.treeholes[::-1])

blueprints/qa.py
from flask import Blueprint, render_template, request, g, redirect, url_for
from .forms import TreeholeForm, ReplyForm
from models import TreeholeModel, ReplyModel
from exts import db
from decorators import login_required

qa_bp = Blueprint('qa', __name__, url_prefix='/')

@qa_bp.route('/')
def index():
    treeholes = TreeholeModel.query.order_by(TreeholeModel.create_time.desc()).all()

    return render_template('index.html', treeholes=treeholes)

@qa_bp.route('/qa/create', methods=['GET', 'POST'])
@login_required
def create_treehole():
    if request.method == 'GET':
        return render_template('create.html')
    else:
        form = TreeholeForm(request.form)
        if form.validate():
            title = form.title.data
            content = form.content.data
            treehole = TreeholeModel(title=title, content=content, author = g.user)
            db.session.add(treehole)
            db.session.commit()
            return redirect('/')
        else:
            print(form.errors)
            return redirect(url_for('qa.create_treehole'))

@qa_bp.route('/qa/detail/<int:treehole_id>')
def detail_treehole(treehole_id):
    treehole = TreeholeModel.query.get(treehole_id)
    return render_template('detail.html', treehole=treehole)


@qa_bp.route('/reply', methods=['POST'])
@login_required
def reply():
    form = ReplyForm(request.form)
    if form.validate():
        content = form.content.data
        treehole_id = form.treehole_id.data
        reply = ReplyModel(content=content, treehole_id=treehole_id, author_id=g.user.id)
        db.session.add(reply)
        db.session.commit()
        return redirect(url_for('qa.detail_treehole', treehole_id=treehole_id))
    else:
        print(form.errors)
        return redirect(url_for('qa.detail_treehole', treehole_id = request.form.get('treehole_id')))
    
@qa_bp.route('/search')
def search():
    treehole = request.args.get('treehole')
    if treehole:
        treeholes = TreeholeModel.query.filter(TreeholeModel.title.contains(treehole)).all()
        return render_template('index.html', treeholes=treeholes)
    else:
        return redirect(url_for('qa.index'))
        

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{{ url_for('static', filename='css/base.css') }}">
    {% block head %}
    {% endblock %}
</head>
<body>
    <header>
        <div class="navbar">
            <div class="logo-container">
                <!-- 左侧图片位置 -->
                <img src="/static/images/logo1.jpg" alt="Logo 1" class="logo">
                <img src="/static/images/logo2.jpg" alt="Logo 2" class="logo" style="width: 185px;height: 45px;">
                <h2 style="color: white; text-shadow: rgb(0, 0, 0) 3px 3px 3px;">TreeholeBUAA 北航树洞</h2>
                <a href="{{ url_for('qa.index') }}" class="button">回到首页</a>
            </div>
            <div class="button-container">
                <!-- 右侧按钮位置 -->
                {% if user %}
                <form method="GET" class="search-form" action="{{ url_for('qa.search') }}">
                    <input type="text" name="treehole" placeholder="搜索树洞（关键字）" class="search-input">
                    <button type="submit" class="button">搜索</button>
                </form>
                <a href="{{ url_for('qa.create_treehole') }}" class ="button">创建树洞</a>
                <a href="{{ url_for('auth.manage') }}" class="button">{{user.username}}</a>
                <a href="{{ url_for('auth.logout') }}" class="button">退出登录</a>
                {% else %}
                <form method="GET" class="search-form" action="{{ url_for('qa.search') }}">
                    <input type="text" name="treehole" placeholder="搜索树洞（关键字）" class="search-input">
                    <button type="submit" class="button">搜索</button>
                </form>
                <a href="{{ url_for('auth.login') }}" class="button">登录</a>
                <a href="{{ url_for('auth.register') }}" class="button">注册</a>
                {% endif %}
                
            </div>
        </div>
    </header>

    <main>
        <div class="container">
            {% block content %}
            {% endblock %}
        </div>
    </main>
</body>
</html>

templates/create.html
{% extends 'base.html'%}

{% block head %}
<title>TreeholeBUAA 创建树洞</title>
<link rel="stylesheet" href="{{url_for('static',filename='css/create.css')}}">
{% endblock %}

{% block content %}
<h3 class="page-title">创建树洞</h3>
    <form action="" method="post">
        <div class="form-container">
            <div class="form-group">
                <input type="text" class="form-control"  placeholder="请输入标题" name="title">
            </div>
            <div class="form-group">
                <textarea name="content" placeholder="请输入内容" class="form-control" rows="10"></textarea>
            </div>
            <div class="form-group">
                <button class="btn btn-primary" style="height: 30px;width: 100px; font-size: 15px;font-weight: bold;">立即创建</button>
            </div>
        </div>
    </form>
{% endblock %}

templates/detail.html
{% extends 'base.html'%}

{% block head %}
<title>树洞：{{ treehole.title }}</title>
<link rel="stylesheet" href="{{url_for('static',filename='css/detail.css')}}">
{% endblock %}
{% block content %}
    <h3 class="page-title">{{ treehole.title }}</h3>
    <p class="question-info">
        <span>洞主：{{ treehole.author.username }}&nbsp;&nbsp;&nbsp;&nbsp;</span>
        <span>时间：{{ treehole.create_time }}</span>
    </p>
    <hr>
    <p class="question-content">
        {{ treehole.content }}
    </p>
    <hr>
    <h4>评论:({{treehole.replies|length}})</h4>
    <form action="{{url_for('qa.reply')}}" method="POST">
        <div class="form-group">
            <input name="content" type="text" class="form-control" placeholder="评论不能少于3个字">
            <input type="hidden" name="treehole_id" value="{{treehole.id}}">
        </div>
        <div class="form-group" style="text-align:right;">
            <button  class="btn btn-primary">立即评论</button>
        </div>
    </form>
    <ul class="answer-list">
        {% for reply in treehole.replies%}
        <li><div class="user-info">
            <img src="{{url_for('static',filename='images/avatars.jpg')}}" class="avatar">
            <span class="username">{{reply.author.username}}</span>
            <span class="create-time">{{reply.create_time}}</span>
        </div>
        <p class="answer-content" style="line-height: 1.5;">
            {{reply.content}}
        </p></li>
        {%endfor%}
    </ul>
{% endblock %}

templates/index.html
{% extends 'base.html' %}


{% block head %}
<title>TreeholeBUAA 首页</title>
<link rel="stylesheet" href="{{url_for('static',filename='css/index.css')}}">
{% endblock %}

{% block content %}
    <ul class="treehole-list-group">
        {% for treehole in treeholes %}
        <li>
                <div class="avatar-group">
                    <img src="{{url_for('static',filename='images/avatars.jpg')}}" alt="" class="avatar">
                </div>
                <div class="treehole-group">
                    <p class="treehole-title"><a href="{{ url_for('qa.detail_treehole', treehole_id=treehole.id) }}">{{ treehole.title }}</a></p>
                    <p class="treehole-content">{{ treehole.content }}</p>
                    <div class="treehole-info">
                        <span class="treehole-author">洞主：{{ treehole.author.username }}</span>
                        <span class="treehole-time">时间：{{ treehole.create_time }}</span>
                    </div>
            </div>
    
            </li>
        {% endfor %}
        
    </ul>
{% endblock %}

templates/login.html
{% extends 'base.html' %}

{% block head %}
    <title>TreeholeBUAA 登录</title>
    <link rel="stylesheet" href="{{ url_for('static', filename='css/login.css') }}">
{% endblock %}


{% block content %}
        <h2>TreeholeBUAA 登录</h2>
        <form method="POST" class = "login-form">
            <label for="email">邮箱：</label>
            <input type="email" id="email" name="email" required placeholder="请输入邮箱地址" aria-describedby="emailHelp" class="form-control">
            <small id="emailHelp" class="form-text text-muted">请使用北京航空航天大学邮箱地址（xxx@buaa.edu.cn）</small>

            <label for="password">密码：</label>
            <input type="password" id="password" name="password" required placeholder="请输入密码" class="form-control">

            <input type="submit" value="登录" style="box-shadow: grey 3px 3px 5px;">
        </form>
{% endblock %}
        

templates/manage.html
{% extends "base.html" %}

{% block head %}
<title>TreeholeBUAA {{ user.username }} 的空间</title>
<link rel="stylesheet" href="{{ url_for('static', filename='css/manage.css') }}"> <!-- 引入自定义样式 -->
{% endblock %}

{% block content %}
<div class="manage-container">
    <h1>{{ user.username }} 的TreeholeBUAA空间</h1>
    
    <div class="profile-section">
        <h2>个人信息</h2>
        <p><strong>邮箱:</strong> {{ user.email }}</p>
        <p><strong>注册日期:</strong> {{ user.reg_time }}</p>
        <!-- 其他个人信息 -->
    </div>

    <div class="settings-section">
        <h2>设置</h2>
        <a href="{{url_for('auth.update_username')}}" class="setbutton">申请新的TreeholeBUAA ID</a>
        <a href="{{url_for('auth.update_pswd')}}" class="setbutton">更改密码</a>
        <a href="{{url_for('auth.manage_treeholes')}}" class="setbutton">查看我的树洞</a>
    </div>

    
</div>
{% endblock %}

templates/my_treeholes.html
{% extends 'base.html' %}

{% block head %}
<title>TreeholeBUAA 我的树洞</title>
<link rel="stylesheet" href="{{ url_for('static',filename='css/my_treeholes.css') }}">
{% endblock %}

{% block content %}
<ul class="treehole-list-group">
    {% for treehole in treeholes %}
    <li>
            <div class="avatar-group">
                <img src="{{url_for('static',filename='images/avatars.jpg')}}" alt="" class="avatar">
            </div>
            <div class="treehole-group">
                <p class="treehole-title"><a href="{{ url_for('qa.detail_treehole', treehole_id=treehole.id) }}">{{ treehole.title }}</a></p>
                <p class="treehole-content">{{ treehole.content }}</p>
                <div class="treehole-info">
                    <span class="treehole-author">洞主：{{ treehole.author.username }}</span>
                    <span class="treehole-time">时间：{{ treehole.create_time }}</span>
                </div>
        </div>

        </li>
    {% endfor %}
    
</ul>
{% endblock %}

templates/register.html
{% extends 'base.html' %}


{% block head %}
    <title>TreeholeBUAA 注册</title>
    <link rel="stylesheet" href="{{ url_for('static', filename='css/register.css') }}">
    <script src="https://apps.bdimg.com/libs/jquery/2.1.4/jquery.min.js"></script>
    <script src="{{ url_for('static', filename='js/register.js') }}"></script>
{% endblock %}

{% block content %}
<h2>TreeholeBUAA 注册</h2>
<form method="POST" action="{{ url_for('auth.register') }}" class="form-register">
    <label for="email">邮箱：</label>
    <input type="email" id="email" name="email" required placeholder="请输入邮箱地址" aria-describedby="emailHelp" class="form-control">
    <small id="emailHelp" class="form-text text-muted">请使用北京航空航天大学邮箱地址（xxx@buaa.edu.cn）</small>

    <div class="form-group">
        <label for="captcha">验证码：</label>
        <input type="text" id="captcha" name="captcha" required placeholder="请输入六位验证码" class="form-control">
        <button type="button" id="captchaBtn" class="captcha-btn">获取验证码</button>
    </div>

    <label for="password">密码：</label>
    <input type="password" id="password" name="password" required placeholder="请输入8-20位包含大小写字母及数字的密码" class="form-control">

    <label for="password_confirm">确认密码：</label>
    <input type="password" id="password_confirm" name="password_confirm" required placeholder="请再次输入密码" class="form-control">

    <input type="submit" value="注册" class="register-btn">
</form>
{% endblock %}

templates/update_pswd.html
{% extends 'base.html' %}

{% block head %}
<title>TreeholeBUAA 修改密码</title>
<link rel="stylesheet" href="{{ url_for('static', filename='css/update_pswd.css') }}">
{% endblock %}

{% block content %}
<h2>TreeholeBUAA 更改密码</h2>
        <form method="POST" class = "update-pswd-form">
            <input type="hidden" name="key" id="key" value="{{ user.id }}">
            <label for="password">旧密码：</label>
            <input type="password" id="old_password" name="old_password" required placeholder="请输入旧密码" class="form-control">

            <label for="new_password">新密码：</label>
            <input type="password" id="new_password" name="new_password" required placeholder="请输入新密码" class="form-control">

            <label for="confirm_password">确认新密码：</label>
            <input type="password" id="new_password_confirm" name="new_password_confirm" required placeholder="请确认新密码" class="form-control">

            <input type="submit" value="提交" style="box-shadow: grey 3px 3px 5px;">
        </form>
{% endblock %}

templates/update_username.html
{% extends 'base.html' %}

{% block head %}
<title>TreeholeBUAA 申请新的TreeholeBUAA ID</title>
<link rel="stylesheet" href="{{ url_for('static', filename='css/update_username.css') }}">
<link rel="stylesheet" href="{{ url_for('static', filename='css/register.css') }}">
<script src="https://apps.bdimg.com/libs/jquery/2.1.4/jquery.min.js"></script>
<script src="{{ url_for('static', filename='js/register.js') }}"></script>
{% endblock %}

{% block content %}
<h1>申请新的TreeholeBUAA ID</h1>
<form method="POST" class = "update-username-form">
    <input type="hidden" name="key" id="key" value="{{ user.id }}">

    <label for="email">邮箱：</label>
    <input type="email" id="email" name="email" required placeholder="请输入邮箱地址" aria-describedby="emailHelp" class="form-control">
    <small id="emailHelp" class="form-text text-muted">请使用注册账号时的邮箱</small>

    <div class="form-group">
        <label for="captcha">验证码：</label>
        <input type="text" id="captcha" name="captcha" required placeholder="请输入六位验证码" class="form-control">
        <button type="button" id="captchaBtn" class="captcha-btn">获取验证码</button>
    </div>
    <input type="submit" value="确认更改我的TreeholeBUAA ID" style="box-shadow: grey 3px 3px 5px;" class="button">
    <small class="form-text text-muted">这将跳转到登录页面，下次登录后可以查看新的TreeholeBUAA ID，同时原有的TreeholeBUAA ID将失效。</small>
</form>
{% endblock %}